"use client";

import * as React from "react";
import { useEffect, useMemo, useState } from "react";
import type { LucideIcon } from "lucide-react";
import { Activity, ArrowLeft, ArrowRight, Bell, BookOpenText, CalendarDays, Check, ChevronDown, ChevronRight, CircleHelp, Clock3, Compass, Download, ExternalLink, Eye, EyeOff, Gift, Heart, Link2, LockKeyhole, Menu, MessageCircle, MoreHorizontal, Network, Plus, Search, Send, Settings2, ShieldCheck, Sparkles, Trash2, Users, X } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { FirstRunDialog, type FirstRunAnswers } from "@/components/first-run";
import { YouMark } from "@/components/you-mark";
import { flushSync } from "react-dom";
import { connectors, events, insights, memories as seedMemories, people as seedPeople, type Insight, type Memory, type MemoryStatus, type Person } from "@/data/demo";

type View = "for-you" | "memory" | "people" | "relationships" | "timeline" | "reminders" | "ask" | "connections" | "settings";
type Modal = "add-memory" | "edit-person" | "add-date" | "reminder" | "action" | "reset" | "setup" | null;
type Answer = { question: string; text: string; sources: string[] };
type PageTool = { name: string; title: string; description: string; inputSchema: object; annotations: { readOnlyHint: boolean; untrustedContentHint: boolean }; execute: (input: unknown) => unknown | Promise<unknown> };
type PageModelContext = { registerTool: (tool: PageTool, options?: { signal?: AbortSignal }) => void | Promise<void> };
type SavedState = { memories: Memory[]; people: Person[]; dismissed: string[]; handled: string[]; reminders: string[]; mutedKinds: string[]; permission: Record<string, boolean>; onboarded: boolean; introSeen: boolean; selectedSources: string[]; selectedHarness: string; routines: string[]; publicDiscovery: boolean; publicProfileUrl: string };

const initialState: SavedState = { memories: seedMemories, people: seedPeople, dismissed: [], handled: [], reminders: [], mutedKinds: [], permission: {}, onboarded: false, introSeen: false, selectedSources: [], selectedHarness: "", routines: [], publicDiscovery: false, publicProfileUrl: "" };
const storageKey = "you-prototype-v2";
const nav: { id: View; label: string; icon: LucideIcon }[] = [
  { id: "for-you", label: "For you", icon: Sparkles }, { id: "memory", label: "Memory", icon: BookOpenText }, { id: "people", label: "People", icon: Users }, { id: "relationships", label: "Relationships", icon: Network }, { id: "timeline", label: "Timeline", icon: Clock3 }, { id: "reminders", label: "Reminders", icon: Bell }, { id: "ask", label: "Ask YOU", icon: MessageCircle }, { id: "connections", label: "Connections", icon: Link2 }, { id: "settings", label: "Privacy & access", icon: ShieldCheck },
];
const memoryCategories = ["All", "People", "Preferences", "Routines", "Plans", "Wellbeing"] as const;
const statusNames: Record<MemoryStatus, string> = { known: "Known", inferred: "Inferred", unknown: "Unknown", disputed: "Needs review" };
const introQuestions = ["What do you remember about me?", "Who should I catch up with?", "Why do you think Mike likes golf?", "What should I make time for?", "What don't you know yet?"];

function readState(): SavedState {
  if (typeof window === "undefined") return initialState;
  try {
    const raw = window.localStorage.getItem(storageKey);
    if (!raw) return initialState;
    const stored = JSON.parse(raw) as Partial<SavedState>;
    return { ...initialState, ...stored, memories: stored.memories ?? seedMemories, people: stored.people ?? seedPeople };
  } catch { return initialState; }
}

function Avatar({ person, size = "md" }: { person: Person; size?: "sm" | "md" | "lg" }) {
  return <div className={`avatar avatar-${person.color} avatar-${size}`} aria-hidden="true">{person.initials}</div>;
}

function Status({ memory }: { memory: Memory }) {
  return <span className={`status status-${memory.status}`}><span className="status-dot" />{statusNames[memory.status]}{memory.confidence !== null ? ` · ${Math.round(memory.confidence * 100)}%` : ""}</span>;
}

function SectionTitle({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) {
  return <div className="section-head"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div>;
}

function memoryAnswer(question: string, data: SavedState): Answer {
  const q = question.toLowerCase();
  const allowed = (id: string) => data.memories.some(m => m.id === id && m.privacy === "available");
  const source = (ids: string[]) => data.memories.filter(m => ids.includes(m.id) && m.privacy === "available").map(m => `${m.label} · ${m.source} · ${statusNames[m.status]}${m.confidence !== null ? ` ${Math.round(m.confidence * 100)}%` : ""}`);
  if (/golf|mike like|mike interested/.test(q)) return allowed("m-mike-golf") ? { question, text: "I think Mike may like golf. It came up in three sample conversations, but he has not confirmed it as an ongoing interest. I would treat this as a clue, not a fact.", sources: source(["m-mike-golf"]) } : { question, text: "I don’t have an available memory about Mike’s interests.", sources: [] };
  if (/birthday|anniversary|date/.test(q)) { const details = [allowed("m-mike-birthday") ? "Mike’s birthday is October 2" : "", allowed("m-anniversary") ? "your anniversary with Morgan is October 17" : "", allowed("m-mom-anniversary") ? "I do not know Mom’s anniversary yet" : ""].filter(Boolean); return { question, text: details.length ? `${details.join("; ")}.` : "I don’t have an available memory of those dates.", sources: source(["m-mike-birthday", "m-anniversary", "m-mom-anniversary"]) }; }
  if (/who.*(catch|talk|contact)|recently/.test(q)) return { question, text: "Chris stands out. In the sample history, you usually catch up every two to three weeks and it has been eleven weeks. You can decide whether now is a good time to reach out.", sources: ["Sample interaction history · 14 months", "Last contact · July 4"] };
  if (/work|time|make time|tonight|concert|music/.test(q)) return { question, text: `${allowed("m-live-music") ? "You saved small outdoor concerts as something you enjoy. " : ""}${allowed("m-work") ? "Your sample calendar also shows a busy work stretch. " : ""}I cannot verify tonight’s events, read device activity, or book tickets in this prototype.`, sources: source(["m-work", "m-live-music"]) };
  if (/don't|unknown|missing|not know/.test(q)) return { question, text: `${allowed("m-mom-anniversary") ? "I don’t know Mom’s anniversary. " : ""}Device activity is not connected, so I will not make claims about TikTok or other app use.`, sources: source(["m-mom-anniversary"]) };
  if (/steve|commitment|open loop/.test(q)) return { question, text: data.handled.includes("steve") ? "You marked the contractor follow-up with Steve as handled." : "A sample email suggests you offered Steve a contractor’s number. I have not seen a follow-up in the demo history.", sources: ["Sample email · September 10", "Commitment state · local to this browser"] };
  return { question, text: "I can answer from the memories currently shown in this prototype. I know about your close people, some saved preferences, a few sample events, and possible open loops. For anything outside those records, I don’t know yet.", sources: ["YOU demo memory · visible in Memory"] };
}

export default function HomePage() {
  const [data, setData] = useState<SavedState>(initialState);
  const [hydrated, setHydrated] = useState(false);
  const [view, setView] = useState<View>("for-you");
  const [personId, setPersonId] = useState<string | null>(null);
  const [selectedMemory, setSelectedMemory] = useState<Memory | null>(null);
  const [selectedInsight, setSelectedInsight] = useState<Insight | null>(null);
  const [modal, setModal] = useState<Modal>(null);
  const [mobileNav, setMobileNav] = useState(false);
  const [query, setQuery] = useState("");
  const [memoryFilter, setMemoryFilter] = useState<string>("All");
  const [search, setSearch] = useState("");
  const [askInput, setAskInput] = useState("");
  const [answers, setAnswers] = useState<Answer[]>([]);
  const [draft, setDraft] = useState({ label: "", value: "", subjectId: "self", date: "", reminder: "" });
  const [editingName, setEditingName] = useState("");
  const [editingRelation, setEditingRelation] = useState("");
  const [introOpen, setIntroOpen] = useState(false);
  const [toast, setToast] = useState("");
  const [todayText, setTodayText] = useState("Today");

  useEffect(() => { const saved = readState(); setData(saved); setIntroOpen(!saved.introSeen); setHydrated(true); setTodayText(new Intl.DateTimeFormat("en-US", { weekday: "long", month: "long", day: "numeric" }).format(new Date())); }, []);
  useEffect(() => { if (hydrated) window.localStorage.setItem(storageKey, JSON.stringify(data)); }, [data, hydrated]);
  useEffect(() => { if (toast) { const timer = window.setTimeout(() => setToast(""), 3300); return () => window.clearTimeout(timer); } }, [toast]);
  useEffect(() => {
    if (!hydrated) return;
    const context = (document as Document & { modelContext?: PageModelContext }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    const register = async (tool: PageTool) => { try { await context.registerTool(tool, { signal: lifecycle.signal }); } catch { /* Browser has no usable WebMCP registry. */ } };
    void register({ name: "you_find_memories", title: "Find available memories", description: "Search memories that this prototype marks available to agents. Returns state, confidence, and provenance.", inputSchema: { type: "object", properties: { query: { type: "string" } }, required: ["query"], additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: true }, execute(input) { if (!input || typeof input !== "object" || typeof (input as { query?: unknown }).query !== "string") throw new Error("query must be a string"); const q = (input as { query: string }).query.trim().toLowerCase(); if (!q) throw new Error("query cannot be empty"); return { memories: data.memories.filter(m => m.privacy === "available" && `${m.label} ${m.value} ${m.category}`.toLowerCase().includes(q)).slice(0, 10).map(({ id, subjectId, label, value, status, confidence, source, observedAt }) => ({ id, subjectId, label, value, status, confidence, source, observedAt })) }; } });
    void register({ name: "you_add_memory", title: "Add a memory", description: "Add a user provided memory to YOU and show it in the memory browser. The new memory is marked known with You as the source.", inputSchema: { type: "object", properties: { label: { type: "string" }, value: { type: "string" }, subjectId: { type: "string" } }, required: ["label", "value"], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: true }, execute(input) { if (!input || typeof input !== "object") throw new Error("Expected an object"); const args = input as { label?: unknown; value?: unknown; subjectId?: unknown }; if (typeof args.label !== "string" || !args.label.trim() || typeof args.value !== "string" || !args.value.trim()) throw new Error("label and value are required strings"); const subjectId = typeof args.subjectId === "string" ? args.subjectId : "self"; if (subjectId !== "self" && !data.people.some(p => p.id === subjectId)) throw new Error("Unknown subjectId"); const date = new Date().toISOString().slice(0, 10); const fact: Memory = { id: `webmcp-${Date.now()}`, subjectId, category: "Preferences", label: args.label.trim(), value: args.value.trim(), status: "known", confidence: 1, source: "You · page tool", sourceType: "user", observedAt: date, lastVerified: date, evidence: "Added through the visible YOU prototype page tool.", privacy: "available" }; flushSync(() => { setData(prev => ({ ...prev, memories: [fact, ...prev.memories] })); setView("memory"); }); return { id: fact.id, status: "saved", visibleIn: "Memory" }; } });
    return () => lifecycle.abort();
  }, [hydrated, data.memories, data.people]);

  const selectedPerson = data.people.find(p => p.id === personId) ?? null;
  const visibleInsights = insights.filter(i => !data.dismissed.includes(i.id) && !data.handled.includes(i.id) && !data.mutedKinds.includes(i.kind));
  const filteredMemories = useMemo(() => data.memories.filter(m => (memoryFilter === "All" || m.category === memoryFilter) && `${m.label} ${m.value} ${m.source} ${data.people.find(p => p.id === m.subjectId)?.name ?? "You"}`.toLowerCase().includes(search.toLowerCase())), [data.memories, data.people, memoryFilter, search]);
  const filteredPeople = useMemo(() => data.people.filter(p => `${p.name} ${p.relation} ${p.details}`.toLowerCase().includes(search.toLowerCase())), [data.people, search]);

  function navigate(next: View) { setView(next); setPersonId(null); setMobileNav(false); setSearch(""); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function openPerson(id: string) { setView("people"); setPersonId(id); setMobileNav(false); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function updateMemory(id: string, patch: Partial<Memory>) { setData(prev => ({ ...prev, memories: prev.memories.map(m => m.id === id ? { ...m, ...patch } : m) })); setSelectedMemory(prev => prev?.id === id ? { ...prev, ...patch } : prev); }
  function removeMemory(id: string) { setData(prev => ({ ...prev, memories: prev.memories.filter(m => m.id !== id) })); setSelectedMemory(null); setToast("Memory removed from this browser."); }
  function dismiss(id: string) { setData(prev => ({ ...prev, dismissed: [...prev.dismissed, id] })); setToast("Suggestion dismissed."); }
  function remind(id: string) { setData(prev => ({ ...prev, reminders: [...new Set([...prev.reminders, id])] })); setToast("Added to your reminders."); }
  function createReminder() { const value = draft.reminder.trim(); if (!value) return; setData(prev => ({ ...prev, reminders: [`custom:${value}`, ...prev.reminders] })); setDraft(prev => ({ ...prev, reminder: "" })); setModal(null); setToast("Reminder added."); }
  function completeReminder(id: string) { setData(prev => ({ ...prev, reminders: prev.reminders.filter(item => item !== id) })); setToast("Reminder marked handled."); }
  function reminderLabel(id: string) { if (id.startsWith("custom:")) return id.slice(7); return ({ chris: "Reach out to Chris", work: "Check in about your work week", "work-break": "Make space for a break", concert: "Look for outdoor live music", steve: "Follow up with Steve" } as Record<string, string>)[id] ?? id; }
  function handleInsight(insight: Insight) { setSelectedInsight(insight); if (insight.id === "steve") { setData(prev => ({ ...prev, handled: [...prev.handled, "steve"] })); setToast("Marked handled."); } else if (insight.id === "chris") { navigate("ask"); ask("Draft a warm note to Chris"); } else setModal("action"); }
  function ask(question?: string) { const q = (question ?? askInput).trim(); if (!q) return; setAnswers(prev => [...prev, memoryAnswer(q, data)]); setAskInput(""); setView("ask"); }
  function addMemory(category: Memory["category"] = "Preferences") { if (!draft.label.trim() || !draft.value.trim()) return; const newMemory: Memory = { id: `user-${Date.now()}`, subjectId: draft.subjectId, category, label: draft.label.trim(), value: draft.value.trim(), status: "known", confidence: 1, source: "You", sourceType: "user", observedAt: new Date().toISOString().slice(0, 10), lastVerified: new Date().toISOString().slice(0, 10), evidence: "You added this directly.", privacy: "available" }; setData(prev => ({ ...prev, memories: [newMemory, ...prev.memories] })); setDraft({ label: "", value: "", subjectId: "self", date: "", reminder: "" }); setModal(null); setToast("Saved to your memory."); }
  function addDate() { if (!selectedPerson || !draft.label.trim() || !draft.date) return; setDraft(prev => ({ ...prev, value: new Date(`${prev.date}T12:00:00`).toLocaleDateString("en-US", { month: "long", day: "numeric" }), subjectId: selectedPerson.id })); const newMemory: Memory = { id: `date-${Date.now()}`, subjectId: selectedPerson.id, category: "People", label: draft.label.trim(), value: new Date(`${draft.date}T12:00:00`).toLocaleDateString("en-US", { month: "long", day: "numeric" }), status: "known", confidence: 1, source: "You", sourceType: "user", observedAt: new Date().toISOString().slice(0, 10), lastVerified: new Date().toISOString().slice(0, 10), evidence: "You added this date directly.", privacy: "available" }; setData(prev => ({ ...prev, memories: [newMemory, ...prev.memories] })); setModal(null); setDraft({ label: "", value: "", subjectId: "self", date: "", reminder: "" }); setToast("Important date added."); }
  function savePerson() { if (!selectedPerson || !editingName.trim()) return; setData(prev => ({ ...prev, people: prev.people.map(p => p.id === selectedPerson.id ? { ...p, name: editingName.trim(), relation: editingRelation.trim() } : p) })); setModal(null); setToast("Person updated."); }
  function exportData() { const blob = new Blob([JSON.stringify({ format: "you-memory-export", version: 1, exportedAt: new Date().toISOString(), ...data }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "you-memory-export.json"; link.click(); URL.revokeObjectURL(url); setToast("Your memory export is ready."); }
  function finishOnboarding(answers: FirstRunAnswers) { const date = new Date().toISOString().slice(0, 10); const items = [
    { label: "A person who matters", value: answers.person, category: "People" as const },
    { label: "Something that brings me joy", value: answers.joy, category: "Preferences" as const },
    { label: "What I want help with", value: answers.focus, category: "Plans" as const },
    { label: "How to check in", value: answers.style, category: "Wellbeing" as const },
  ].filter(item => item.value.trim()).map((item, index): Memory => ({ id: `engram-${Date.now()}-${index}`, subjectId: "self", category: item.category, label: item.label, value: item.value.trim(), status: "known", confidence: 1, source: "You · first engram", sourceType: "user", observedAt: date, lastVerified: date, evidence: "You shared this in the first engram questionnaire.", privacy: "available" })); setData(prev => ({ ...prev, memories: [...items, ...prev.memories], onboarded: true, introSeen: true, selectedSources: answers.sources, selectedHarness: answers.harness, routines: answers.routines, publicDiscovery: answers.publicDiscovery, publicProfileUrl: answers.publicProfileUrl })); setModal(null); setToast("Your first engram is saved."); }

  return <div className="app-shell">
    {introOpen && <div className="intro-screen" role="dialog" aria-modal="true" aria-label="Welcome to YOU"><div className="intro-center"><div className="intro-mark"><YouMark /></div><div className="intro-words"><span className="intro-hi">Hi.</span><span className="intro-name">I’m YOU.</span></div><p>The last agent you’ll ever need.</p><div className="intro-buttons"><button onClick={() => { setIntroOpen(false); setData(prev => ({ ...prev, introSeen: true })); setModal("setup"); }}>Begin <ArrowRight size={17} /></button><button onClick={() => { setIntroOpen(false); setData(prev => ({ ...prev, introSeen: true })); }}>Explore the demo</button></div></div></div>}
    <aside className={`sidebar ${mobileNav ? "sidebar-open" : ""}`}>
      <div className="sidebar-top"><button className="brand" onClick={() => navigate("for-you")}><span className="brand-mark"><YouMark /></span><span><strong>YOU</strong><small>Your personal context</small></span></button><button className="mobile-close" aria-label="Close navigation" onClick={() => setMobileNav(false)}><X size={20} /></button></div>
      <div className="nav-caption">YOUR SPACE</div>
      <nav aria-label="Main navigation" className="nav-list">{nav.map(item => { const Icon = item.icon; return <button key={item.id} className={`nav-link ${view === item.id ? "active" : ""}`} onClick={() => navigate(item.id)}><Icon size={18} strokeWidth={1.8} /><span>{item.label}</span>{item.id === "memory" && <span className="nav-count">{data.memories.length}</span>}</button>; })}</nav>
      <div className="sidebar-bottom"><div className="privacy-mini"><LockKeyhole size={15} /><span>Fictional data · stored in this browser</span></div><div className="user-row"><span className="user-avatar">A</span><span><strong>Alex</strong><small>Personal space</small></span><MoreHorizontal size={17} /></div></div>
    </aside>
    {mobileNav && <button aria-label="Close navigation" className="nav-scrim" onClick={() => setMobileNav(false)} />}
    <div className="app-main">
      <header className="topbar"><button className="mobile-menu" aria-label="Open navigation" onClick={() => setMobileNav(true)}><Menu size={21} /></button><div className="breadcrumb"><span>YOU</span><ChevronRight size={14} /><strong>{selectedPerson?.name ?? nav.find(n => n.id === view)?.label}</strong></div><div className="top-actions"><span className="demo-pill"><span /> Fictional demo</span><button className="icon-button" aria-label="Go to privacy settings" onClick={() => navigate("settings")}><ShieldCheck size={18} /></button></div></header>
      <main className="content">
        {data.onboarded && (view === "connections" || view === "settings") && <div className="setup-current"><span className="setup-current-icon"><Sparkles size={18} /></span><div><strong>Your setup choices</strong><p>{data.selectedHarness ? `${data.selectedHarness} selected as your first assistant` : "No assistant selected"} · {data.selectedSources.length} possible sources · {data.routines.length} routine preferences. These are saved locally; no accounts or jobs are active.</p></div></div>}
        {view === "relationships" && <><SectionTitle eyebrow="YOUR CIRCLE" title="The people around you" description="Connections help YOU understand context across the people in your life. Every link can be reviewed." /><div className="graph-root-card"><span className="user-avatar">A</span><div><strong>Alex</strong><span>Your relationships, in context</span></div><Network size={19} /></div><div className="graph-branches">{[{ title: "Family", ids: ["morgan", "mom", "dad"], detail: "The people closest to home" }, { title: "Friends", ids: ["mike", "chris", "steve"], detail: "Shared history and open loops" }, { title: "Connected through Mike", ids: ["sarah"], detail: "Sarah is Mike’s wife; Emma is their daughter" }].map(branch => <section className="graph-branch" key={branch.title}><div className="graph-branch-heading"><span className="graph-line-dot" /><div><h2>{branch.title}</h2><p>{branch.detail}</p></div></div><div className="graph-people">{branch.ids.map(id => { const person = data.people.find(p => p.id === id); return person ? <button key={id} onClick={() => openPerson(id)}><Avatar person={person} size="sm" /><span><strong>{person.name}</strong><small>{person.relation}</small></span><ChevronRight size={15} /></button> : null; })}</div></section>)}</div><div className="graph-note"><ShieldCheck size={17} /><p>This is a sample map. A future connector will propose relationship links with evidence; you decide whether to keep them.</p></div></>}
        {view === "reminders" && <><SectionTitle eyebrow="OPEN LOOPS" title="Reminders" description="A small place for the things you don’t want to lose track of." action={<button className="primary-button" onClick={() => { setDraft(prev => ({ ...prev, reminder: "" })); setModal("reminder"); }}><Plus size={16} /> Add reminder</button>} /><div className="reminders-list">{data.reminders.length ? data.reminders.map((id, index) => <div className="reminder-card" key={`${id}-${index}`}><span className="reminder-icon"><Bell size={18} /></span><div><strong>{reminderLabel(id)}</strong><p>{id.startsWith("custom:") ? "You added this" : "From a YOU suggestion"} · Saved in this browser</p></div><button className="outline-button compact" onClick={() => completeReminder(id)}><Check size={14} /> Mark handled</button></div>) : <div className="empty-card"><Bell size={27} /><h2>Nothing to remember right now.</h2><p>You can add your own reminder or save one from a suggestion.</p><button className="primary-button" onClick={() => setModal("reminder")}><Plus size={15} /> Add reminder</button></div>}</div><div className="reminder-plan"><Clock3 size={18} /><div><strong>Scheduled follow-ups are on the roadmap.</strong><p>This demo saves reminders locally. Background notifications will need an authorized scheduler and delivery channel.</p></div></div></>}
        {view === "for-you" && <>
          <div className="greeting"><div className="eyebrow">{todayText.toUpperCase()} · YOUR SPACE</div><h1>Good to see you, Alex.</h1><p>Here are a few things I noticed. You decide what’s useful.</p></div>
          {!data.onboarded && <div className="engram-banner"><span className="engram-symbol"><BookOpenText size={21} /></span><div><strong>Make YOU yours</strong><p>Choose possible sources and an assistant, then create your first engram.</p></div><button onClick={() => setModal("setup")}>Begin setup <ArrowRight size={16} /></button></div>}
          <div className="feature-layout"><div className="insight-stack">
            {visibleInsights.length ? visibleInsights.map((insight, index) => <article className={`insight-card ${index === 0 ? "featured" : ""}`} key={insight.id}><div className="insight-top"><span className="insight-kicker"><span className={`kind-icon kind-${insight.kind}`}>{insight.kind === "check-in" ? <Heart size={17} /> : insight.kind === "opportunity" ? <Compass size={17} /> : insight.kind === "relationship" ? <Users size={17} /> : <Check size={17} />}</span>{insight.eyebrow}</span><button className="subtle-icon" aria-label={`Dismiss ${insight.title}`} onClick={() => dismiss(insight.id)}><X size={16} /></button></div><h2>{insight.title}</h2><p>{insight.body}</p><div className="insight-actions"><button className="primary-button" onClick={() => handleInsight(insight)}>{insight.action}<ArrowRight size={16} /></button><button className="text-button" onClick={() => { if (insight.secondary.toLowerCase().includes("remind")) remind(insight.id); else if (insight.secondary.includes("fewer")) { setData(prev => ({ ...prev, mutedKinds: [...prev.mutedKinds, insight.kind] })); setToast("You’ll see fewer suggestions like this."); } else dismiss(insight.id); }}>{insight.secondary}</button><button className="why-button" onClick={() => setSelectedInsight(insight)}><CircleHelp size={15} />Why this?</button></div><div className="insight-evidence"><span className="evidence-dot" />{insight.confidence}<span className="evidence-separator">·</span>{insight.evidence[0]}</div></article>) : <div className="empty-card"><Sparkles size={28} /><h2>You’re all caught up.</h2><p>Dismissed suggestions stay out of your way. Your memory is still here when you need it.</p><button className="text-button" onClick={() => navigate("memory")}>Explore memory <ArrowRight size={16} /></button></div>}
          </div><aside className="context-rail"><div className="rail-card memory-spotlight"><div className="rail-kicker"><BookOpenText size={16} /> A MEMORY IN CONTEXT</div><h3>What I know about you</h3><p>You enjoy small outdoor concerts.</p><div className="memory-proof"><span className="status status-known"><span className="status-dot" />Known · 100%</span><span>You told me</span></div><button className="rail-link" onClick={() => { navigate("memory"); setSelectedMemory(data.memories.find(m => m.id === "m-live-music") ?? null); }}>See the evidence <ArrowRight size={15} /></button></div><div className="rail-card"><div className="rail-kicker"><Activity size={16} /> ABOUT DEVICE ACTIVITY</div><h3>You’re in control</h3><p>I can’t read TikTok or Screen Time here. If a supported connector becomes available, you can choose whether to share aggregate trends.</p><button className="rail-link" onClick={() => navigate("connections")}>Review connections <ArrowRight size={15} /></button></div><div className="rail-note"><ShieldCheck size={17} /><span>Suggestions use visible evidence. Uncertain patterns stay uncertain.</span></div></aside></div>
        </>}
        {view === "memory" && <><SectionTitle eyebrow="YOUR CONTEXT" title="What YOU remembers" description="Each memory has a source, a confidence level, and a choice about who can use it." action={<button className="primary-button" onClick={() => { setDraft({ label: "", value: "", subjectId: "self", date: "", reminder: "" }); setModal("add-memory"); }}><Plus size={17} /> Add memory</button>} /><div className="memory-summary"><div><strong>{data.memories.filter(m => m.status === "known").length}</strong><span>Known</span></div><div><strong>{data.memories.filter(m => m.status === "inferred").length}</strong><span>Inferred</span></div><div><strong>{data.memories.filter(m => m.status === "unknown").length}</strong><span>Unknown</span></div><div className="memory-summary-note"><ShieldCheck size={17} /><span>Inference never silently becomes fact.</span></div></div><div className="toolbar"><div className="search-field"><Search size={17} /><input aria-label="Search memories" placeholder="Search memories, people, or sources" value={search} onChange={e => setSearch(e.target.value)} /></div><div className="filter-scroll">{memoryCategories.map(category => <button key={category} className={`filter-chip ${memoryFilter === category ? "selected" : ""}`} onClick={() => setMemoryFilter(category)}>{category}</button>)}</div></div><div className="memory-list">{filteredMemories.map(m => <button className="memory-row" key={m.id} onClick={() => setSelectedMemory(m)}><span className="memory-row-icon">{m.category === "People" ? <Users size={19} /> : m.category === "Preferences" ? <Heart size={19} /> : m.category === "Routines" ? <Activity size={19} /> : m.category === "Plans" ? <CalendarDays size={19} /> : <ShieldCheck size={19} />}</span><span className="memory-row-main"><strong>{m.label}</strong><span>{m.value}</span><small>{data.people.find(p => p.id === m.subjectId)?.name ?? "You"} · {m.source}</small></span><span className="memory-row-side"><Status memory={m} /><ChevronRight size={18} /></span></button>)}{!filteredMemories.length && <div className="empty-card">No memories match this search.</div>}</div></>}
        {view === "people" && !selectedPerson && <><SectionTitle eyebrow="YOUR PEOPLE" title="People who matter" description="A private, living picture of the people in your world." action={<button className="outline-button" onClick={() => navigate("memory")}><BookOpenText size={16} /> See memories</button>} /><div className="toolbar"><div className="search-field"><Search size={17} /><input aria-label="Search people" placeholder="Search people" value={search} onChange={e => setSearch(e.target.value)} /></div></div>{["Inner circle", "Close", "Regular"].map(group => { const groupPeople = filteredPeople.filter(p => p.importance === group); return groupPeople.length ? <section className="people-section" key={group}><h2>{group}</h2><div className="people-grid">{groupPeople.map(p => <button key={p.id} className="person-card" onClick={() => openPerson(p.id)}><Avatar person={p} /><span className="person-card-copy"><strong>{p.name}</strong><span>{p.relation}</span><small>Last contact · {p.lastContact}</small>{p.nextMoment && <em>{p.nextMoment}</em>}</span><ChevronRight size={17} /></button>)}</div></section> : null; })}</>}
        {view === "people" && selectedPerson && <><button className="back-link" onClick={() => setPersonId(null)}><ArrowLeft size={16} /> All people</button><div className="profile-head"><Avatar person={selectedPerson} size="lg" /><div className="profile-head-copy"><div className="eyebrow">{selectedPerson.importance.toUpperCase()}</div><h1>{selectedPerson.name}</h1><p>{selectedPerson.relation}</p></div><button className="outline-button" onClick={() => { setEditingName(selectedPerson.name); setEditingRelation(selectedPerson.relation); setModal("edit-person"); }}><Settings2 size={16} /> Edit profile</button></div><div className="profile-grid"><div><div className="profile-callout"><div className="rail-kicker"><Sparkles size={16} /> A LITTLE CONTEXT</div><p>{selectedPerson.details}</p><span>Last interaction · {selectedPerson.lastContact}</span></div><div className="subsection-head"><h2>What I remember</h2><button onClick={() => { setDraft({ label: "", value: "", subjectId: selectedPerson.id, date: "", reminder: "" }); setModal("add-memory"); }}><Plus size={16} /> Add fact</button></div><div className="memory-list">{data.memories.filter(m => m.subjectId === selectedPerson.id).map(m => <button className="memory-row" key={m.id} onClick={() => setSelectedMemory(m)}><span className="memory-row-main"><strong>{m.label}</strong><span>{m.value}</span><small>{m.source}</small></span><span className="memory-row-side"><Status memory={m} /><ChevronRight size={17} /></span></button>)}</div><div className="subsection-head"><h2>Recent history</h2></div><div className="mini-timeline">{events.filter(e => e.personId === selectedPerson.id).map(e => <div key={e.id}><span>{e.date}</span><div><strong>{e.title}</strong><small>{e.detail} · {e.source}</small></div></div>)}</div></div><aside className="profile-side"><div className="rail-card"><div className="rail-kicker"><CalendarDays size={16} /> IMPORTANT DATES</div><h3>{selectedPerson.nextMoment ?? "No date saved yet"}</h3><button className="rail-link" onClick={() => { setDraft({ label: "", value: "", subjectId: selectedPerson.id, date: "", reminder: "" }); setModal("add-date"); }}><Plus size={15} /> Add important date</button></div><div className="rail-card"><div className="rail-kicker"><Network size={16} /> RELATIONSHIPS</div><p>{selectedPerson.id === "mike" ? "Sarah Thompson · spouse" : selectedPerson.id === "sarah" ? "Mike Thompson · spouse\nEmma · daughter" : selectedPerson.id === "morgan" ? "Alex · spouse" : "Connections can be added as YOU learns more."}</p>{["mike", "sarah"].includes(selectedPerson.id) && <button className="rail-link" onClick={() => openPerson(selectedPerson.id === "mike" ? "sarah" : "mike")}>View person <ArrowRight size={15} /></button>}</div></aside></div></>}
        {view === "timeline" && <><SectionTitle eyebrow="YOUR STORY" title="A timeline of context" description="The events behind YOU’s memories and suggestions. Demo events are labeled by source." /><div className="timeline-list">{events.map(e => <div className="timeline-item" key={e.id}><div className="timeline-date">{e.date}</div><span className="timeline-node" /><div className="timeline-card"><span className="eyebrow">{e.source}</span><h2>{e.title}</h2><p>{e.detail}</p>{e.personId && <button className="rail-link" onClick={() => openPerson(e.personId!)}>View {data.people.find(p => p.id === e.personId)?.name} <ArrowRight size={15} /></button>}</div></div>)}</div></>}
        {view === "ask" && <><SectionTitle eyebrow="ASK YOUR MEMORY" title="Ask YOU" description="Answers come from the memory you can inspect. When I don’t know, I’ll say so." /><div className="ask-layout"><div className="ask-panel"><div className="ask-conversation">{answers.length ? answers.map((a, index) => <div className="answer-block" key={`${a.question}-${index}`}><div className="user-question">{a.question}</div><div className="you-answer"><span className="tiny-brand"><YouMark /></span><div><p>{a.text}</p><div className="answer-sources"><strong>Based on</strong>{a.sources.map(s => <span key={s}>{s}</span>)}</div></div></div></div>) : <div className="ask-empty"><span className="ask-symbol"><Sparkles size={28} /></span><h2>What’s on your mind?</h2><p>Ask about people, plans, patterns, or what YOU remembers. This demo answers from its visible sample memory.</p></div>}</div><form className="ask-form" onSubmit={e => { e.preventDefault(); ask(); }}><input aria-label="Ask YOU a question" placeholder="Ask anything about your world…" value={askInput} onChange={e => setAskInput(e.target.value)} /><button aria-label="Send question" type="submit"><ArrowRight size={19} /></button></form></div><aside className="ask-prompts"><h3>Try asking</h3>{introQuestions.map(q => <button key={q} onClick={() => ask(q)}>{q}<ArrowRight size={15} /></button>)}</aside></div></>}
        {view === "connections" && <><SectionTitle eyebrow="YOUR INPUTS & OUTPUTS" title="Connections" description="Choose what YOU may learn from, and which assistants may read your memory." /><div className="connection-intro"><div><span className="connection-intro-icon"><Network size={24} /></span><h2>One memory. Many assistants.</h2><p>YOU keeps the context. Claude, OpenAI, Codex, local models, and future tools can access only the scopes you grant through an open API or MCP adapter.</p></div><div className="harness-tags"><span>Claude</span><span>OpenAI</span><span>Codex</span><span>Any MCP client</span></div></div><div className="subsection-head"><h2>Sources & capabilities</h2><span className="muted-small">Connections are simulated in this prototype</span></div><div className="connector-grid">{connectors.map(c => <div className="connector-card" key={c.id}><div className="connector-top"><span className="connector-icon">{c.id === "screentime" ? <Activity size={20} /> : c.id === "events" ? <Compass size={20} /> : c.id === "mcp" ? <Network size={20} /> : <Link2 size={20} />}</span><span className={`connector-state ${c.status}`}>{c.status === "demo" ? "Demo source" : c.status === "available" ? "Placeholder" : "Exploring"}</span></div><h3>{c.name}</h3><p>{c.description}</p><small>{c.data}</small><button className="rail-link" onClick={() => setToast(`${c.name} is a placeholder. No live account was connected.`)}>How it would work <ArrowRight size={15} /></button></div>)}</div><div className="access-card"><div><div className="rail-kicker"><ShieldCheck size={16} /> AGENT ACCESS</div><h2>Grant access per assistant, per topic.</h2><p>A future MCP/API server will enforce scopes such as people.read, preferences.read, insights.read, and memory.write. Every read can be audited or revoked.</p></div><button className="outline-button" onClick={() => navigate("settings")}>View privacy controls <ArrowRight size={16} /></button></div></>}
        {view === "settings" && <><SectionTitle eyebrow="YOU STAY IN CHARGE" title="Privacy & access" description="See what is stored, control what agents may read, and take your data with you." /><div className="settings-grid"><div><section className="settings-card"><div className="settings-card-head"><span className="settings-icon"><LockKeyhole size={18} /></span><div><h2>Storage</h2><p>This prototype stores demo changes only in this browser’s local storage.</p></div></div><div className="setting-row"><div><strong>Local mode</strong><span>No account or server sync is active.</span></div><span className="status status-known"><span className="status-dot" />On</span></div><div className="setting-row"><div><strong>Export your memory</strong><span>Download people, facts, states, and preferences as JSON.</span></div><button className="outline-button compact" onClick={exportData}><Download size={15} /> Export</button></div></section><section className="settings-card"><div className="settings-card-head"><span className="settings-icon"><Eye size={18} /></span><div><h2>Suggestion boundaries</h2><p>Tell YOU when it can speak up.</p></div></div>{[{ id: "check-in", name: "Gentle wellbeing check-ins", desc: "Patterns can prompt a question, never a diagnosis." }, { id: "opportunity", name: "Plans and local ideas", desc: "Suggest activities based on your interests." }, { id: "relationship", name: "People reminders", desc: "Surface important dates and changed rhythms." }].map(k => <div className="setting-row" key={k.id}><div><strong>{k.name}</strong><span>{k.desc}</span></div><Switch aria-label={k.name} checked={!data.mutedKinds.includes(k.id)} onCheckedChange={checked => setData(prev => ({ ...prev, mutedKinds: checked ? prev.mutedKinds.filter(x => x !== k.id) : [...prev.mutedKinds, k.id] }))} /></div>)}</section></div><aside><section className="settings-card"><div className="settings-card-head"><span className="settings-icon"><Network size={18} /></span><div><h2>Agent permissions</h2><p>Future clients start with no access.</p></div></div>{["Claude", "OpenAI / ChatGPT", "Codex", "Other MCP clients"].map(name => <div className="setting-row" key={name}><div><strong>{name}</strong><span>Not connected</span></div><span className="off-label">Off</span></div>)}<button className="rail-link" onClick={() => navigate("connections")}>How agent access works <ArrowRight size={15} /></button></section><section className="settings-card danger-card"><h2>Reset this demo</h2><p>Clear changes made in this browser and restore the sample data.</p><button className="danger-button" onClick={() => setModal("reset")}><Trash2 size={16} /> Reset demo data</button></section></aside></div></>}
      </main>
    </div>

    <Dialog open={!!selectedMemory} onOpenChange={open => !open && setSelectedMemory(null)}><DialogContent className="memory-dialog"><DialogHeader><DialogTitle>{selectedMemory?.label}</DialogTitle><DialogDescription>Memory and evidence</DialogDescription></DialogHeader>{selectedMemory && <div className="memory-detail"><Status memory={selectedMemory} /><p className="detail-value">{selectedMemory.value}</p><div className="detail-grid"><div><span>About</span><strong>{data.people.find(p => p.id === selectedMemory.subjectId)?.name ?? "You"}</strong></div><div><span>Category</span><strong>{selectedMemory.category}</strong></div><div><span>Source</span><strong>{selectedMemory.source}</strong></div><div><span>Observed</span><strong>{selectedMemory.observedAt}</strong></div><div><span>Last verified</span><strong>{selectedMemory.lastVerified ?? "Not verified"}</strong></div></div><div className="evidence-box"><strong>Why YOU believes this</strong><p>{selectedMemory.evidence}</p></div><div className="detail-control"><div><strong>Available to future agents</strong><span>Private and excluded memories stay out of agent responses.</span></div><Switch aria-label="Available to agents" checked={selectedMemory.privacy === "available"} onCheckedChange={checked => updateMemory(selectedMemory.id, { privacy: checked ? "available" : "private" })} /></div><div className="detail-actions"><button className="outline-button compact" onClick={() => { updateMemory(selectedMemory.id, { status: "known", confidence: 1, source: "You", sourceType: "user", lastVerified: new Date().toISOString().slice(0, 10), evidence: "You confirmed this memory." }); setToast("Confirmed by you."); }}><Check size={15} /> Confirm</button><button className="outline-button compact" onClick={() => { updateMemory(selectedMemory.id, { status: "disputed", confidence: null, evidence: `${selectedMemory.evidence} You marked this for review.` }); setToast("Marked for review."); }}><CircleHelp size={15} /> Correct later</button><button className="danger-link" onClick={() => removeMemory(selectedMemory.id)}><Trash2 size={15} /> Remove</button></div></div>}</DialogContent></Dialog>
    <Dialog open={!!selectedInsight} onOpenChange={open => !open && setSelectedInsight(null)}><DialogContent className="memory-dialog"><DialogHeader><DialogTitle>Why YOU surfaced this</DialogTitle><DialogDescription>{selectedInsight?.title}</DialogDescription></DialogHeader>{selectedInsight && <div className="memory-detail"><span className="status status-inferred"><span className="status-dot" />{selectedInsight.confidence}</span><p className="detail-value">{selectedInsight.body}</p><div className="evidence-box"><strong>Evidence in this demo</strong>{selectedInsight.evidence.map(line => <p key={line}>• {line}</p>)}</div><p className="small-note">YOU should ask before acting on uncertain or sensitive patterns. This sample uses no live accounts.</p></div>}</DialogContent></Dialog>
    <Dialog open={modal === "add-memory"} onOpenChange={open => !open && setModal(null)}><DialogContent><DialogHeader><DialogTitle>Add to memory</DialogTitle><DialogDescription>Facts you add directly are marked “Known · You told me.”</DialogDescription></DialogHeader><div className="form-stack"><label>About<select value={draft.subjectId} onChange={e => setDraft({ ...draft, subjectId: e.target.value })}><option value="self">You</option>{data.people.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>What should I remember?<input autoFocus value={draft.label} onChange={e => setDraft({ ...draft, label: e.target.value })} placeholder="e.g. Favorite restaurant" /></label><label>Detail<textarea value={draft.value} onChange={e => setDraft({ ...draft, value: e.target.value })} placeholder="Write the detail in your own words" /></label><button className="primary-button" disabled={!draft.label.trim() || !draft.value.trim()} onClick={() => addMemory()}>Save memory <ArrowRight size={16} /></button></div></DialogContent></Dialog>
    <Dialog open={modal === "edit-person"} onOpenChange={open => !open && setModal(null)}><DialogContent><DialogHeader><DialogTitle>Edit person</DialogTitle><DialogDescription>Keep names and relationship context accurate.</DialogDescription></DialogHeader><div className="form-stack"><label>Name<input value={editingName} onChange={e => setEditingName(e.target.value)} /></label><label>Relationship<input value={editingRelation} onChange={e => setEditingRelation(e.target.value)} /></label><button className="primary-button" onClick={savePerson}>Save changes <Check size={16} /></button></div></DialogContent></Dialog>
    <Dialog open={modal === "add-date"} onOpenChange={open => !open && setModal(null)}><DialogContent><DialogHeader><DialogTitle>Add an important date</DialogTitle><DialogDescription>For {selectedPerson?.name}. You can revisit or remove it later.</DialogDescription></DialogHeader><div className="form-stack"><label>Occasion<input value={draft.label} onChange={e => setDraft({ ...draft, label: e.target.value })} placeholder="Birthday, anniversary, graduation…" /></label><label>Date<input type="date" value={draft.date} onChange={e => setDraft({ ...draft, date: e.target.value })} /></label><button className="primary-button" disabled={!draft.label.trim() || !draft.date} onClick={addDate}>Save date <Check size={16} /></button></div></DialogContent></Dialog>
    <Dialog open={modal === "action"} onOpenChange={open => !open && setModal(null)}><DialogContent><DialogHeader><DialogTitle>{selectedInsight?.id === "work" ? "Let’s make space" : "Explore this idea"}</DialogTitle><DialogDescription>This is a guided demo. YOU won’t send or book anything.</DialogDescription></DialogHeader><div className="action-body">{selectedInsight?.id === "work" ? <><p>It sounds like your week may be crowded. What would help most right now?</p><button onClick={() => { setModal(null); ask("What should I make time for?"); }}><MessageCircle size={17} /> Talk it through <ArrowRight size={16} /></button><button onClick={() => { remind("work-break"); setModal(null); }}><Bell size={17} /> Remind me to take a break <ArrowRight size={16} /></button></> : <><p>A future local events connector could check availability and link to official ticket sellers. Tonight’s concert is only a sample suggestion.</p><button onClick={() => { remind("concert"); setModal(null); }}><Bell size={17} /> Remind me about live music <ArrowRight size={16} /></button><button onClick={() => { setModal(null); navigate("connections"); }}><Compass size={17} /> See event connector plan <ArrowRight size={16} /></button></>}</div></DialogContent></Dialog>
    <Dialog open={modal === "reset"} onOpenChange={open => !open && setModal(null)}><DialogContent><DialogHeader><DialogTitle>Reset demo data?</DialogTitle><DialogDescription>All changes saved in this browser will be removed. The original fictional data will return.</DialogDescription></DialogHeader><div className="detail-actions"><button className="outline-button" onClick={() => setModal(null)}>Cancel</button><button className="danger-button" onClick={() => { window.localStorage.removeItem(storageKey); setData(initialState); setAnswers([]); setPersonId(null); setModal(null); setToast("Demo restored."); }}>Reset demo</button></div></DialogContent></Dialog>
    <Dialog open={modal === "reminder"} onOpenChange={open => !open && setModal(null)}><DialogContent><DialogHeader><DialogTitle>Add a reminder</DialogTitle><DialogDescription>Keep a thought or commitment close. This demo saves it in your browser.</DialogDescription></DialogHeader><div className="form-stack"><label>What should YOU remind you about?<input autoFocus value={draft.reminder} onChange={e => setDraft({ ...draft, reminder: e.target.value })} placeholder="e.g. Ask Mom how her appointment went" onKeyDown={e => { if (e.key === "Enter") createReminder(); }} /></label><button className="primary-button" disabled={!draft.reminder.trim()} onClick={createReminder}>Save reminder <Check size={16} /></button></div></DialogContent></Dialog>
    <FirstRunDialog open={modal === "setup"} onClose={() => setModal(null)} onFinish={finishOnboarding} />
    {toast && <div role="status" className="toast"><Check size={16} />{toast}</div>}
  </div>;
}
